   apiVersion: v1
   kind: PersistentVolume
   metadata:
     name: alertmanager-main-db1
   spec:
     accessModes:
     - ReadWriteOnce
     capacity:
       storage: 2Gi
     nfs:
       path: /exports/alertmanager-main-db1
       server: lab-openshift-lb.localdomain.ar
     persistentVolumeReclaimPolicy: Retain
