   apiVersion: v1
   kind: PersistentVolume
   metadata:
     name: logging-volume
   spec:
     accessModes:
     - ReadWriteOnce
     capacity:
       storage: 100Gi
     nfs:
       path: /exports/logging
       server: lab-openshift-lb.localdomain.ar
     persistentVolumeReclaimPolicy: Retain
