apiVersion: v1
   kind: PersistentVolume
   metadata:
     name: prometheus-k8s-db0
   spec:
     accessModes:
     - ReadWriteOnce
     capacity:
       storage: 50Gi
     nfs:
       path: /exports/prometheus-k8s-db0
       server: lab-openshift-lb.localdomain.ar
     persistentVolumeReclaimPolicy: Retain
